export const HomeCarouselData=[
    {
        image:"https://upload.wikimedia.org/wikipedia/en/d/dc/MemoirsOfAGeisha.jpg",
        path:"/Literature/Classics/Memoirs_Of_A_Geisha"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/en/d/dc/MemoirsOfAGeisha.jpg",
        path:"/Literature/Classics/Memoirs_Of_A_Geisha"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/en/d/dc/MemoirsOfAGeisha.jpg",
        path:"/Literature/Classics/Memoirs_Of_A_Geisha"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/en/d/dc/MemoirsOfAGeisha.jpg",
        path:"/Literature/Classics/Memoirs_Of_A_Geisha"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/en/d/dc/MemoirsOfAGeisha.jpg",
        path:"/Literature/Classics/Memoirs_Of_A_Geisha"
    }
]